# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Minimum Coverage 80%

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: devmasx/coverage-check-action@v1.2.0
      with:
        type: simplecov
        min_coverage: 80
        token: token-token
